# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{clock}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pivotal Labs"]
  s.date = %q{2010-11-12}
  s.description = %q{Works exactly like Ruby's standard Time object, but in test mode adds some nice methods for setting or manually advancing time.}
  s.email = %q{pivotal-opensource@googlegroups.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "lib/clock.rb",
     "lib/clock/clock.rb",
     "lib/clock/mock_clock.rb",
     "lib/clock/real_clock.rb",
     "lib/clock/time_zone_proxy.rb"
  ]
  s.homepage = %q{http://github.com/pivotal/clock}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A wrapper for Ruby's Time object that includes a mock for manipulating time in tests}
  s.test_files = [
    "spec/clock_spec.rb",
     "spec/rails_app/app/controllers/application_controller.rb",
     "spec/rails_app/app/helpers/application_helper.rb",
     "spec/rails_app/config/application.rb",
     "spec/rails_app/config/boot.rb",
     "spec/rails_app/config/environment.rb",
     "spec/rails_app/config/environments/development.rb",
     "spec/rails_app/config/environments/production.rb",
     "spec/rails_app/config/environments/test.rb",
     "spec/rails_app/config/initializers/backtrace_silencers.rb",
     "spec/rails_app/config/initializers/inflections.rb",
     "spec/rails_app/config/initializers/mime_types.rb",
     "spec/rails_app/config/initializers/secret_token.rb",
     "spec/rails_app/config/initializers/session_store.rb",
     "spec/rails_app/config/routes.rb",
     "spec/rails_app/db/seeds.rb",
     "spec/rails_app/test/performance/browsing_test.rb",
     "spec/rails_app/test/test_helper.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.0.0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.0.0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.0.0"])
  end
end

